import { 
  DocumentItem, 
  ReceiptItem, 
  SubscriptionItem, 
  WarrantyItem, 
  NoteItem, 
  BookmarkItem, 
  TimelineEvent, 
  VaultSuggestion 
} from '../types';

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    title: 'T.C. Pasaport & Vize Belgesi',
    category: 'Identity',
    fileType: 'pdf',
    fileSize: '2.4 MB',
    previewUrl: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=600&auto=format&fit=crop&q=80',
    tags: ['Pasaport', 'Kimlik', 'Seyahat'],
    ocrText: 'TÜRKİYE CUMHURİYETİ PASAPORTU - PASSPORT NO: U12345678 - GEÇERLİLİK TARİHİ: 15 EKİM 2027',
    description: 'Biyometrik pasaport taranmış yüksek çözünürlüklü kopya ve geçerli Schengen vizesi.',
    createdAt: '2026-06-12',
    updatedAt: '2026-06-12',
    isFavorite: true,
    isArchived: false,
  },
  {
    id: 'doc-2',
    title: 'Konut Kira Sözleşmesi 2026-2027',
    category: 'Property',
    fileType: 'pdf',
    fileSize: '4.1 MB',
    previewUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=600&auto=format&fit=crop&q=80',
    tags: ['Kira', 'Daire', 'Sözleşme'],
    ocrText: 'KİRA SÖZLEŞMESİ - KİRALAYAN: AHMET YILMAZ - KİRACI: ALİ CAN - AYLIK KİRA: 32.000 TL',
    description: 'Kadıköy 2+1 daire resmi kira kontratı ve kefil imza tutanağı.',
    createdAt: '2026-05-01',
    updatedAt: '2026-05-01',
    isFavorite: true,
    isArchived: false,
  },
  {
    id: 'doc-3',
    title: 'Araç Kasko & Trafik Poliçesi',
    category: 'Vehicle',
    fileType: 'pdf',
    fileSize: '1.8 MB',
    previewUrl: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=600&auto=format&fit=crop&q=80',
    tags: ['Araç', 'Kasko', 'Sigorta'],
    ocrText: 'ANADOLU SİGORTA KASKO POLİÇESİ - PLAKA: 34 ABC 789 - BİTİŞ TARİHİ: 20 EYLÜL 2026',
    description: 'Genişletilmiş kasko ve zorunlu mali sorumluluk sigorta poliçesi.',
    createdAt: '2026-04-15',
    updatedAt: '2026-04-15',
    isFavorite: false,
    isArchived: false,
  },
  {
    id: 'doc-4',
    title: 'Tam Kapsamlı Özel Sağlık Sigortası',
    category: 'Health',
    fileType: 'pdf',
    fileSize: '3.2 MB',
    previewUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&auto=format&fit=crop&q=80',
    tags: ['Sağlık', 'Sigorta', 'Poliçe'],
    ocrText: 'ACIBADEM SİGORTA ÖZEL SAĞLIK POLİÇESİ - POLİÇE NO: H-9928172',
    description: 'Ayakta ve yatarak tedavi sınırsız teminatlı özel sağlık sigortası kart ve detay metni.',
    createdAt: '2026-01-10',
    updatedAt: '2026-01-10',
    isFavorite: true,
    isArchived: false,
  },
  {
    id: 'doc-5',
    title: 'MacBook Pro M3 Max Faturası',
    category: 'Finance',
    fileType: 'pdf',
    fileSize: '950 KB',
    previewUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    tags: ['Apple', 'Fatura', 'Elektronik'],
    ocrText: 'GÜRGENÇLER APPLE STORE - E-FATURA NO: GRC20250000492 - TUTAR: 114.999 TL',
    description: 'Resmi e-fatura belgesi ve garanti sicil kayıt numarası.',
    createdAt: '2025-11-20',
    updatedAt: '2025-11-20',
    isFavorite: false,
    isArchived: false,
  }
];

export const INITIAL_RECEIPTS: ReceiptItem[] = [
  {
    id: 'rec-1',
    merchant: 'Apple Zorlu Center',
    merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg',
    amount: 114999,
    currency: 'TL',
    date: '2025-11-20',
    category: 'Tech',
    receiptUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    warrantyId: 'war-1',
    notes: 'MacBook Pro 16" M3 Max 36GB RAM 1TB SSD Space Black',
    isFavorite: true,
  },
  {
    id: 'rec-2',
    merchant: 'IKEA Ümraniye',
    merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/c/c5/Ikea_logo.svg',
    amount: 18450,
    currency: 'TL',
    date: '2026-03-14',
    category: 'Home',
    receiptUrl: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&auto=format&fit=crop&q=80',
    notes: 'Markus Çalışma Koltuğu ve Bekant Elektrikli Ayarlanabilir Masa',
    isFavorite: false,
  },
  {
    id: 'rec-3',
    merchant: 'Türk Hava Yolları',
    merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Turkish_Airlines_logo_2019.svg/512px-Turkish_Airlines_logo_2019.svg.png',
    amount: 14200,
    currency: 'TL',
    date: '2026-05-22',
    category: 'Travel',
    receiptUrl: 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=600&auto=format&fit=crop&q=80',
    notes: 'İstanbul - Amsterdam Gidiş Dönüş Uçak Biletleri (2 Kişi)',
    isFavorite: false,
  },
  {
    id: 'rec-4',
    merchant: 'Dyson Türkiye',
    merchantLogo: 'https://upload.wikimedia.org/wikipedia/commons/f/f7/Dyson_logo.svg',
    amount: 24999,
    currency: 'TL',
    date: '2026-02-10',
    category: 'Home',
    warrantyId: 'war-2',
    receiptUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
    notes: 'Dyson V15 Detect Kablosuz Süpürge',
    isFavorite: true,
  }
];

export const INITIAL_SUBSCRIPTIONS: SubscriptionItem[] = [
  {
    id: 'sub-1',
    name: 'iCloud+ 200 GB',
    price: 39.99,
    currency: 'TL',
    billingCycle: 'monthly',
    renewalDate: '2026-08-05',
    category: 'Cloud',
    status: 'active',
    notes: 'Aile paylaşımı açık, tüm cihaz yedeklemeleri ve şifreli saklama.',
  },
  {
    id: 'sub-2',
    name: 'Spotify Premium Family',
    price: 99.99,
    currency: 'TL',
    billingCycle: 'monthly',
    renewalDate: '2026-08-12',
    category: 'Entertainment',
    status: 'active',
    notes: '6 kişilik aile planı.',
  },
  {
    id: 'sub-3',
    name: 'ChatGPT Plus',
    price: 20,
    currency: 'USD',
    billingCycle: 'monthly',
    renewalDate: '2026-08-18',
    category: 'Software',
    status: 'active',
    notes: 'GPT-4o ve Advanced Voice Modu erişimi.',
  },
  {
    id: 'sub-4',
    name: 'Adobe Creative Cloud',
    price: 689,
    currency: 'TL',
    billingCycle: 'monthly',
    renewalDate: '2026-08-25',
    category: 'Work',
    status: 'active',
    notes: 'Photoshop, Illustrator, Premiere Pro ve Acrobat Pro paketi.',
  },
  {
    id: 'sub-5',
    name: 'Netflix Ultra HD',
    price: 299.99,
    currency: 'TL',
    billingCycle: 'monthly',
    renewalDate: '2026-08-01',
    category: 'Entertainment',
    status: 'active',
    notes: '4 ekran 4K HDR yayın hakkı.',
  }
];

export const INITIAL_WARRANTIES: WarrantyItem[] = [
  {
    id: 'war-1',
    productName: 'MacBook Pro 16" M3 Max',
    brand: 'Apple',
    imageUrl: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&auto=format&fit=crop&q=80',
    purchaseDate: '2025-11-20',
    expiryDate: '2027-11-20',
    receiptId: 'rec-1',
    serialNumber: 'C02G901XMD6M',
    status: 'active',
    notes: 'AppleCare+ Uzatılmış 2 Yıl Garanti ve Kaza Sorumluluğu.',
  },
  {
    id: 'war-2',
    productName: 'Sony WH-1000XM5 Kulaklık',
    brand: 'Sony',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    purchaseDate: '2024-09-01',
    expiryDate: '2026-09-01',
    serialNumber: 'SN-99812401',
    status: 'expiring_soon',
    notes: 'Garanti süresi yakında doluyor (35 gün kaldı). Ped değişimi için servis randevusu alınabilir.',
  },
  {
    id: 'war-3',
    productName: 'Dyson V15 Detect Süpürge',
    brand: 'Dyson',
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
    purchaseDate: '2026-02-10',
    expiryDate: '2028-02-10',
    receiptId: 'rec-4',
    serialNumber: 'DY-V15-TR-4910',
    status: 'active',
    notes: 'Dyson Türkiye Resmi 2 Yıl Parça ve İşçilik Garantisi.',
  }
];

export const INITIAL_NOTES: NoteItem[] = [
  {
    id: 'note-1',
    title: 'Acil Durum Sağlık & Kan Grubu Bilgileri',
    content: `• Kan Grubu: A Rh Positive
• Düzenli Kullanılan İlaçlar: Yok
• Alerjiler: Penisilin alerjisi mevcut
• Acil Durum Yakını: Aslı Yılmaz (Eş) - 0532 111 22 33
• Aile Hekimi: Dr. Mehmet Öz - Kadıköy 4 Nolu ASM`,
    tags: ['Sağlık', 'Acil', 'Önemli'],
    createdAt: '2026-01-05',
    updatedAt: '2026-07-20',
    isPinned: true,
  },
  {
    id: 'note-2',
    title: 'Ev Wi-Fi & Abonelik Hizmet Kodları',
    content: `• Wi-Fi Ağı: Kapsule_Home_5G
• Superonline Müşteri No: 8829104
• Elektrik Abone No (CK Boğaziçi): 10294819
• Doğalgaz Abone No (İGDAŞ): 5019284
• Bina Yönetimi & Kapıcı: Hüseyin Efendi - 0535 444 55 66`,
    tags: ['Ev', 'Kodlar', 'Abone'],
    createdAt: '2026-02-14',
    updatedAt: '2026-05-10',
    isPinned: true,
  },
  {
    id: 'note-3',
    title: 'Araç Periyodik Bakım Geçmişi (34 ABC 789)',
    content: `• 60.000 KM Bakımı (Mart 2026): Yağ, hava ve polen filtresi değişti. Ön fren balataları yenilendi (Yetkili Servis).
• Sonraki Bakım: 75.000 KM veya Mart 2027.
• Muayene Geçerlilik Bitiş: 14 Kasım 2027.`,
    tags: ['Araç', 'Bakım'],
    createdAt: '2026-03-20',
    updatedAt: '2026-03-20',
    isPinned: false,
  }
];

export const INITIAL_BOOKMARKS: BookmarkItem[] = [
  {
    id: 'bm-1',
    title: 'Apple Developer Documentation',
    url: 'https://developer.apple.com/documentation/',
    domain: 'developer.apple.com',
    description: 'Human Interface Guidelines, Swift API references and design systems.',
    faviconUrl: 'https://developer.apple.com/favicon.ico',
    previewUrl: 'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=600&auto=format&fit=crop&q=80',
    tags: ['Geliştirici', 'Tasarım', 'Apple'],
    savedAt: '2026-06-18',
  },
  {
    id: 'bm-2',
    title: 'e-Devlet Kapısı — Soy Ağacı & Nüfus Kayıt',
    url: 'https://www.turkiye.gov.tr/',
    domain: 'turkiye.gov.tr',
    description: 'T.C. e-Devlet kapısı resmi belge alma ve hizmet erişim portalı.',
    faviconUrl: 'https://www.turkiye.gov.tr/favicon.ico',
    previewUrl: 'https://images.unsplash.com/photo-1450133064473-71024230f91b?w=600&auto=format&fit=crop&q=80',
    tags: ['Resmi', 'Devlet', 'Belge'],
    savedAt: '2026-05-11',
  },
  {
    id: 'bm-3',
    title: 'Linear — Purpose-built product development',
    url: 'https://linear.app',
    domain: 'linear.app',
    description: 'Linear helps streamline software projects, sprints, tasks, and bug tracking.',
    faviconUrl: 'https://linear.app/favicon.ico',
    previewUrl: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    tags: ['İş', 'Üretkenlik'],
    savedAt: '2026-04-02',
  }
];

export const INITIAL_TIMELINE: TimelineEvent[] = [
  {
    id: 'tl-1',
    title: 'T.C. Pasaport Kasaya Eklendi',
    description: 'Biyometrik pasaport belgesi ve schengen vizesi dijital kasada arşivlendi.',
    category: 'document',
    date: '2026-06-12',
    linkedItemId: 'doc-1',
    itemType: 'document',
  },
  {
    id: 'tl-2',
    title: 'THY Uçak Bileti Faturası Kaydedildi',
    description: 'Amsterdam seyahati uçuş biletleri ve e-faturası kasa kayıtlarına işlendi.',
    category: 'receipt',
    date: '2026-05-22',
    linkedItemId: 'rec-3',
    itemType: 'receipt',
  },
  {
    id: 'tl-3',
    title: 'Konut Kira Kontratı Yenilendi',
    description: 'Kadıköy daire yeni dönem kira kontratı imzalandı ve belgelendi.',
    category: 'document',
    date: '2026-05-01',
    linkedItemId: 'doc-2',
    itemType: 'document',
  },
  {
    id: 'tl-4',
    title: 'Dyson V15 Süpürge Garanti Başlangıcı',
    description: '2 Yıllık Dyson Türkiye garantisi ve faturası sisteme bağlandı.',
    category: 'warranty',
    date: '2026-02-10',
    linkedItemId: 'war-3',
    itemType: 'warranty',
  },
  {
    id: 'tl-5',
    title: 'MacBook Pro M3 Max Satın Alındı',
    description: 'Zorlu Apple Store faturası ve AppleCare+ garanti sertifikası kasaya kaydoldu.',
    category: 'receipt',
    date: '2025-11-20',
    linkedItemId: 'rec-1',
    itemType: 'receipt',
  }
];

export const INITIAL_SUGGESTIONS: VaultSuggestion[] = [
  {
    id: 'sug-1',
    title: 'Sony WH-1000XM5 Garanti Süresi Doluyor',
    description: 'Kulaklık garantinizin bitmesine 35 gün kaldı. Servis ihtiyacınız varsa kontrol etmenizi öneririz.',
    type: 'urgent',
    actionLabel: 'Garantiyi İncele',
    targetScreen: 'warranties',
    linkedItemId: 'war-2',
    date: '2026-09-01',
  },
  {
    id: 'sug-2',
    title: 'Araç Kasko Poliçesi Yenileme',
    description: '34 ABC 789 plaka kaskonuzun bitimine 2 ay var. Teklifleri inceleyebilirsiniz.',
    type: 'reminder',
    actionLabel: 'Poliçeyi Gör',
    targetScreen: 'documents',
    linkedItemId: 'doc-3',
    date: '2026-09-20',
  },
  {
    id: 'sug-3',
    title: 'Pasaport Süresi Kontrolü',
    description: 'T.C. Pasaportunuzun geçerlilik süresi 2027 Ekim ayında sona eriyor. Vize başvuruları için yeterli süreniz var.',
    type: 'tip',
    actionLabel: 'Detay',
    targetScreen: 'documents',
    linkedItemId: 'doc-1',
  }
];
